name: disease_prediction
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - abseil-cpp=20211102.0=h6b3803e_1
  - altair=4.2.0=pyhd8ed1ab_1
  - appnope=0.1.3=pyhd8ed1ab_0
  - arrow-cpp=8.0.0=py310h6b3e42c_0
  - asttokens=2.0.8=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - aws-c-common=0.6.8=h1a28f6b_0
  - aws-c-event-stream=0.1.6=hc377ac9_5
  - aws-checksums=0.1.11=h1a28f6b_1
  - aws-sdk-cpp=1.8.185=h4a942e0_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - boost-cpp=1.80.0=h04f872d_0
  - brotli=1.0.9=h1c322ee_7
  - brotli-bin=1.0.9=h1c322ee_7
  - brotlipy=0.7.0=py310hf8d0d8f_1004
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.9.24=h4653dfc_0
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py310he00a5c5_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py310hbe9552e_0
  - commonmark=0.9.1=py_0
  - cryptography=38.0.1=py310h4fe9c50_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.6.3=py310hc6dc59f_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.1.1=pyhd8ed1ab_0
  - freetype=2.12.1=hd633e50_0
  - future=0.18.2=py310hbe9552e_5
  - gflags=2.2.2=hc88da5d_1004
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.29=pyhd8ed1ab_0
  - glog=0.6.0=h6da1cb0_0
  - grpc-cpp=1.46.1=h64f8b41_0
  - icu=70.1=h6b3803e_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310hbe9552e_0
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - ipykernel=6.16.0=pyh736e0ef_0
  - ipython=8.5.0=pyhd1c38e8_1
  - ipywidgets=8.0.2=pyhd8ed1ab_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=he4db4b2_2
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py310hbe9552e_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - krb5=1.19.3=hf9b2bbe_0
  - lcms2=2.12=had6a04f_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1c322ee_7
  - libbrotlidec=1.0.9=h1c322ee_7
  - libbrotlienc=1.0.9=h1c322ee_7
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.85.0=hd538317_0
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.10=hbae9a57_4
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_25
  - libgfortran5=11.3.0=hdaf2cc0_25
  - liblapack=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.47.0=h232270b_1
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.38=h76d750c_0
  - libprotobuf=3.20.1=hb5ab8b9_4
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.39.4=h76d750c_0
  - libssh2=1.10.0=hb80f160_3
  - libthrift=0.13.0=hd358383_6
  - libtiff=4.4.0=hfa0b094_4
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libxgboost=1.6.2=cpu_h13cf1d8_0
  - libzlib=1.2.12=h03a7124_4
  - llvm-openmp=14.0.4=hd125106_0
  - lz4-c=1.9.3=hbdafb3b_1
  - markupsafe=2.1.1=py310hf8d0d8f_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numpy=1.23.3=py310h5d7c261_0
  - openjpeg=2.5.0=h5d4e404_1
  - openssl=1.1.1q=ha287fd2_0
  - orc=1.7.4=hb613a79_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.5.0=py310h2b830bf_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310h173adc3_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - protobuf=3.20.1=py310hb07a4bc_0
  - psutil=5.9.2=py310h8e9501a_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=1.6.2=cpu_py310ha244a38_0
  - pyarrow=8.0.0=py310hf303d72_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeck=0.7.1=pyh6c4a22f_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pympler=1.0.1=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py310hf8d0d8f_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.6=hbce4517_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-tzdata=2022.4=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.4=pyhd8ed1ab_0
  - pytz-deprecation-shim=0.1.0.post0=py310hbe9552e_2
  - pyyaml=6.0=py310hf8d0d8f_4
  - pyzmq=24.0.1=py310hc407298_0
  - re2=2022.04.01=h6b3803e_0
  - readline=8.1.2=h46ed386_0
  - requests=2.28.1=pyhd8ed1ab_1
  - rich=12.6.0=pyhd8ed1ab_0
  - scikit-learn=1.1.2=py310h3d7afdd_0
  - scipy=1.9.1=py310ha0d8a01_0
  - semver=2.13.0=pyh9f0ad1d_0
  - setuptools=65.4.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.9=h39c3846_1
  - stack_data=0.5.1=pyhd8ed1ab_0
  - streamlit=1.13.0=pyhd8ed1ab_1
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=he1e0b03_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py310h02f21da_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022d=h191b570_0
  - tzlocal=4.2=py310hbe9552e_1
  - urllib3=1.26.11=pyhd8ed1ab_0
  - utf8proc=2.6.1=h1a28f6b_0
  - validators=0.18.2=pyhd3deb0d_0
  - watchdog=2.1.9=py310h02f21da_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - xgboost=1.6.2=cpu_py310h6b766a5_0
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.9.0=pyhd8ed1ab_0
  - zlib=1.2.12=h03a7124_4
  - zstd=1.5.2=h8128057_4
prefix: /Users/guillechuma/miniconda3/envs/disease_prediction
